/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuan1;

/**
 * @author Hieu Pham
 */
public class formRailFenceCiper extends javax.swing.JFrame {

    /**
     * Creates new form formRailFenceCiper
     */
    public formRailFenceCiper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPlainText = new javax.swing.JTextField();
        jTextFieldKey = new javax.swing.JTextField();
        jTextFieldCipherText = new javax.swing.JTextField();
        jButtonEncypt = new javax.swing.JButton();
        jButtonDecypt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Thuật toán mã hóa Rail Fence Cipher");

        jLabel2.setText("Plain text:");

        jLabel3.setText("Key");

        jLabel4.setText("Cipher text:");

        jButtonEncypt.setText("Encypt");
        jButtonEncypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncyptActionPerformed(evt);
            }
        });

        jButtonDecypt.setText("Dencypt");
        jButtonDecypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecyptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonEncypt)
                                                .addGap(34, 34, 34)
                                                .addComponent(jButtonDecypt))
                                        .addComponent(jTextFieldPlainText, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCipherText)
                                        .addComponent(jTextFieldKey, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jTextFieldPlainText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextFieldKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonEncypt)
                                        .addComponent(jButtonDecypt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextFieldCipherText, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncyptActionPerformed
        // TODO add your handling code here:
        int k = Integer.valueOf(jTextFieldKey.getText());
        String s = jTextFieldPlainText.getText();
        int n = s.length();
        int sd, sc;
        sd = k;
        sc = n / sd + 1;
        char hr[][] = new char[sd][sc];
        int c = 0, d = 0;
        int soDu = n % sd;
        for (int i = 0; i < n; i++) {
            hr[d][c] = s.charAt(i);
            d++;
            if (d == k) {
                c++;
                d = 0;
            }
        }
        String kq = "";
        int soKyTu = sc;
        for (int i = 0; i < sd; i++) {
            if (i >= soDu) {
                soKyTu = sc - 1;
            }
            for (int j = 0; j < soKyTu; j++) {
                kq += hr[i][j];
            }
        }
        jTextFieldCipherText.setText(kq);
    }//GEN-LAST:event_jButtonEncyptActionPerformed

    private void jButtonDecyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecyptActionPerformed
        // TODO add your handling code here:
        int k = Integer.parseInt(jTextFieldKey.getText());
        String s = jTextFieldCipherText.getText();
        int n = s.length();
        int sd, sc;
        sd = k;
        sc = n / sd + 1;
        int t = 0;
        char hr[][] = new char[sd][sc];
        int soDu = n % sd;
        int soKyTu = sc;
        for (int i = 0; i < sd; i++) {
            if (i >= soDu) {
                soKyTu = sc - 1;
            }
            for (int j = 0; j < soKyTu; j++) {
                hr[i][j] = s.charAt(t);
                t++;
            }
        }
        int c = 0, d = 0;
        String kq = "";
        for (int i = 0; i < n; i++) {
            kq += hr[d][c];
            d++;
            if (d == k) {
                c++;
                d = 0;
            }
        }
        jTextFieldPlainText.setText(kq);
    }//GEN-LAST:event_jButtonDecyptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRailFenceCiper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRailFenceCiper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRailFenceCiper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRailFenceCiper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRailFenceCiper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDecypt;
    private javax.swing.JButton jButtonEncypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldCipherText;
    private javax.swing.JTextField jTextFieldKey;
    private javax.swing.JTextField jTextFieldPlainText;
    // End of variables declaration//GEN-END:variables
}
