/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuan1;

/**
 * @author Hieu Pham
 */
public class formPlayFail extends javax.swing.JFrame {

    char pf[][] = {{'M', 'O', 'N', 'A', 'R'},
            {'C', 'H', 'Y', 'B', 'D'},
            {'E', 'F', 'G', 'I', 'K'},
            {'L', 'P', 'Q', 'S', 'T'},
            {'U', 'V', 'W', 'X', 'Z'}};

    /**
     * Creates new form formPlayFail
     */
    public formPlayFail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPlainText = new javax.swing.JTextField();
        jTextFieldKey = new javax.swing.JTextField();
        jTextFieldCipherText = new javax.swing.JTextField();
        jButtonEncypt = new javax.swing.JButton();
        jButtonDencypt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Bản rõ");

        jLabel2.setText("Khóa");

        jLabel3.setText("Bản mã");

        jTextFieldCipherText.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jButtonEncypt.setText("Encypt");
        jButtonEncypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncyptActionPerformed(evt);
            }
        });

        jButtonDencypt.setText("Dencypt");
        jButtonDencypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDencyptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldKey))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldPlainText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonEncypt)
                                                                .addGap(49, 49, 49)
                                                                .addComponent(jButtonDencypt)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(jTextFieldCipherText))))
                                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPlainText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldKey, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldCipherText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonEncypt)
                                        .addComponent(jButtonDencypt))
                                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String thayThe(char a, char b) {
        String vta = timViTri(a);
        String vtb = timViTri(b);
        char x, y;
        if (vta.charAt(0) == vtb.charAt(0)) {
            x = pf[vta.charAt(0) - '0'][((vta.charAt(1) - '0') + 1) % 5];
            y = pf[vtb.charAt(0) - '0'][((vtb.charAt(1) - '0') + 1) % 5];
            return x + "" + y;
        }
        if (vta.charAt(1) == vtb.charAt(1)) {
            x = pf[((vta.charAt(0) - '0') + 1) % 5][vta.charAt(1) - '0'];
            y = pf[((vtb.charAt(0) - '0') + 1) % 5][vtb.charAt(1) - '0'];
            return x + "" + y;
        }
        x = pf[vta.charAt(0) - '0'][vtb.charAt(1) - '0'];
        y = pf[vtb.charAt(0) - '0'][vta.charAt(1) - '0'];
        return x + "" + y;
    }

    private String timViTri(char a) {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (pf[i][j] == a) {
                    return i + "" + j;
                }
            }
        }
        return "";
    }

    private String maHoa(String banRo) {
        int n = banRo.length();
        int i = 0;
        String banMa = "";
        char a, b;
        while (i < n) {
            if (i == n - 1) {
                a = banRo.charAt(i);
                b = 'X';
                i++;
            } else {
                a = banRo.charAt(i);
                b = banRo.charAt(i + 1);

                if (a == b) {
                    b = 'X';
                    i++;
                } else {
                    i += 2;
                }
            }
            banMa += thayThe(a, b);
        }
        return banMa;
    }

    private void jButtonEncyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncyptActionPerformed
        // TODO add your handling code here:
        String banRo = jTextFieldPlainText.getText();
        banRo = banRo.toUpperCase();
        banRo = banRo.replace('J', 'I');
        String banMa = maHoa(banRo);
        jTextFieldCipherText.setText(banMa);
    }//GEN-LAST:event_jButtonEncyptActionPerformed

    private String giaiMa(String banMa) {
        int n = banMa.length();
        int i = 0;
        String banRo = "";
        char a, b;
        while (i < n) {
            a = banMa.charAt(i);
            b = banMa.charAt(i + 1);
            banRo += thayTheNguoc(a, b);
            i += 2;
        }
        return banRo;
    }

    private String thayTheNguoc(char a, char b) {
        String vta = timViTri(a);
        String vtb = timViTri(b);
        char x, y;
        if (vta.charAt(0) == vtb.charAt(0)) {
            x = pf[vta.charAt(0) - '0'][((vta.charAt(1) - '0') - 1 + 5) % 5];
            y = pf[vtb.charAt(0) - '0'][((vtb.charAt(1) - '0') - 1 + 5) % 5];
            return x + "" + y;
        }
        if (vta.charAt(1) == vtb.charAt(1)) {
            x = pf[((vta.charAt(0) - '0') - 1 + 5) % 5][vta.charAt(1) - '0'];
            y = pf[((vtb.charAt(0) - '0') - 1 + 5) % 5][vtb.charAt(1) - '0'];
            return x + "" + y;
        }
        x = pf[vta.charAt(0) - '0'][vtb.charAt(1) - '0'];
        y = pf[vtb.charAt(0) - '0'][vta.charAt(1) - '0'];
        return x + "" + y;
    }

    private void jButtonDencyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDencyptActionPerformed
        // TODO add your handling code here:
        String banMa = jTextFieldCipherText.getText();
        String banRo = giaiMa(banMa);
        int n = banRo.length();
        String br = "";
        for (int i = 0; i < n - 2; i += 2) {
            if (banRo.charAt(i) == banRo.charAt(i + 2)) {
                br += banRo.charAt(i);
            } else {
                br += banRo.charAt(i) + "" + banRo.charAt(i + 1);
            }
        }
        if (banRo.charAt(n - 1) == 'X') {
            br += banRo.charAt(n - 2);
        } else {
            br += banRo.charAt(n - 2) + "" + banRo.charAt(n - 1);
        }
        jTextFieldPlainText.setText(br);
    }//GEN-LAST:event_jButtonDencyptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPlayFail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPlayFail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPlayFail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPlayFail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPlayFail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDencypt;
    private javax.swing.JButton jButtonEncypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldCipherText;
    private javax.swing.JTextField jTextFieldKey;
    private javax.swing.JTextField jTextFieldPlainText;
    // End of variables declaration//GEN-END:variables
}
