/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuan1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hieu Pham
 */
public class formCeasarCipher extends javax.swing.JFrame {

    /**
     * Creates new form formCeasarCipher
     */
    public formCeasarCipher() {
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jLabelHeader = new javax.swing.JLabel();
        jLabelPlainText = new javax.swing.JLabel();
        jLabelKhoa = new javax.swing.JLabel();
        jTextFieldKhoa = new javax.swing.JTextField();
        jButtonEncrypt = new javax.swing.JButton();
        jButtonGhiFile = new javax.swing.JButton();
        jLabelCipherText = new javax.swing.JLabel();
        jButtonDecrypt = new javax.swing.JButton();
        jButtonDocFile = new javax.swing.JButton();
        jTextFieldPlainText = new javax.swing.JTextField();
        jTextFieldCipherText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackground.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("Chương trình mã hóa / Giải mã Ceaser Cipher");
        jLabelHeader.setAlignmentY(0.0F);
        jLabelHeader.setVerifyInputWhenFocusTarget(false);

        jLabelPlainText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelPlainText.setText("Plain text:");

        jLabelKhoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelKhoa.setText("Khóa");
        jLabelKhoa.setPreferredSize(new java.awt.Dimension(35, 35));

        jTextFieldKhoa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldKhoa.setPreferredSize(new java.awt.Dimension(64, 35));

        jButtonEncrypt.setText("Encrypt");
        jButtonEncrypt.setActionCommand("");
        jButtonEncrypt.setDoubleBuffered(true);
        jButtonEncrypt.setMaximumSize(new java.awt.Dimension(75, 25));
        jButtonEncrypt.setMinimumSize(new java.awt.Dimension(75, 25));
        jButtonEncrypt.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncryptActionPerformed(evt);
            }
        });

        jButtonGhiFile.setText("Ghi File");
        jButtonGhiFile.setActionCommand("");
        jButtonGhiFile.setDoubleBuffered(true);
        jButtonGhiFile.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGhiFileActionPerformed(evt);
            }
        });

        jLabelCipherText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelCipherText.setText("Cipher text:");

        jButtonDecrypt.setText("Decrypt");
        jButtonDecrypt.setActionCommand("");
        jButtonDecrypt.setDoubleBuffered(true);
        jButtonDecrypt.setMaximumSize(new java.awt.Dimension(75, 25));
        jButtonDecrypt.setMinimumSize(new java.awt.Dimension(75, 25));
        jButtonDecrypt.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecryptActionPerformed(evt);
            }
        });

        jButtonDocFile.setText("Đọc File");
        jButtonDocFile.setActionCommand("");
        jButtonDocFile.setDoubleBuffered(true);
        jButtonDocFile.setMaximumSize(new java.awt.Dimension(75, 25));
        jButtonDocFile.setMinimumSize(new java.awt.Dimension(75, 25));
        jButtonDocFile.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocFileActionPerformed(evt);
            }
        });

        jTextFieldPlainText.setToolTipText("");
        jTextFieldPlainText.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldCipherText.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPlainText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCipherText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jButtonDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jButtonDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldPlainText, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                        .addComponent(jButtonEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCipherText))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButtonGhiFile, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPlainText)
                    .addComponent(jTextFieldPlainText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGhiFile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCipherText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCipherText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLabelHeader.getAccessibleContext().setAccessibleParent(this);
        jLabelPlainText.getAccessibleContext().setAccessibleParent(this);
        jLabelKhoa.getAccessibleContext().setAccessibleParent(this);
        jTextFieldKhoa.getAccessibleContext().setAccessibleParent(this);
        jButtonEncrypt.getAccessibleContext().setAccessibleName("");
        jButtonEncrypt.getAccessibleContext().setAccessibleParent(this);
        jButtonGhiFile.getAccessibleContext().setAccessibleName("");
        jButtonGhiFile.getAccessibleContext().setAccessibleParent(this);
        jLabelCipherText.getAccessibleContext().setAccessibleParent(this);
        jButtonDecrypt.getAccessibleContext().setAccessibleName("");
        jButtonDecrypt.getAccessibleContext().setAccessibleParent(this);
        jButtonDocFile.getAccessibleContext().setAccessibleName("");
        jButtonDocFile.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private char maHoaKT(char c, int k) {
        if (!Character.isLetter(c)) {
            return c;
        }
        return (char) ((((Character.toUpperCase(c) - 'A') + k) % 26 + 26) % 26 + 'A');
    }

    private String maHoa(String br, int k) {
        String kq = "";
        int n = br.length();
        for (int i = 0; i < n; i++) {
            kq += maHoaKT(br.charAt(i), k);
        }
        return kq;
    }

    private void jButtonEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncryptActionPerformed
        // TODO add your handling code here:
        if (this.jTextFieldPlainText.getText().equals("")||this.jTextFieldKhoa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin!!!");
            return;
        }

        try {
            int k = Integer.valueOf(this.jTextFieldKhoa.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!!!");
            return;
        }

        int k = Integer.valueOf(this.jTextFieldKhoa.getText());
        String br = this.jTextFieldPlainText.getText();
        this.jTextFieldCipherText.setText(maHoa(br, k));
    }//GEN-LAST:event_jButtonEncryptActionPerformed

    private void jButtonGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGhiFileActionPerformed
        // TODO add your handling code here:
        try {
            BufferedWriter bw = null;
            String fileName = "D:\\DLBMTT\\DuLieuEncypt.txt";
            String s = jTextFieldCipherText.getText();
            bw = new BufferedWriter(new FileWriter(fileName));
            bw.write(s);
            bw.close();
            JOptionPane.showMessageDialog(null, "Ghi file thành công!!!");
        } catch (Exception e) {
            Logger.getLogger(formCeasarCipher.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButtonGhiFileActionPerformed

    private void jButtonDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecryptActionPerformed
        // TODO add your handling code here:
        int k = Integer.valueOf(this.jTextFieldKhoa.getText());
        String br = this.jTextFieldCipherText.getText();
        this.jTextFieldPlainText.setText(maHoa(br, -k));
    }//GEN-LAST:event_jButtonDecryptActionPerformed

    private void jButtonDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocFileActionPerformed
        // TODO add your handling code here:
        try {
            BufferedReader br = null;
            String fileName = "D:\\DLBMTT\\DuLieuEncypt.txt";
            String s = jTextFieldCipherText.getText();
            br = new BufferedReader(new FileReader(fileName));
            StringBuffer sb = new StringBuffer();
            JOptionPane.showMessageDialog(null, "Mở file thành công!!!");
            char[] ca = new char[5];
            while (br.ready()) {
                int len = br.read(ca);
                sb.append(ca, 0, len);
            }
            br.close();
            System.out.println("Du lieu la: " + sb);
            jTextFieldPlainText.setText(sb.toString());
        } catch (Exception e) {
            Logger.getLogger(formCeasarCipher.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButtonDocFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCeasarCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCeasarCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCeasarCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCeasarCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCeasarCipher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDecrypt;
    private javax.swing.JButton jButtonDocFile;
    private javax.swing.JButton jButtonEncrypt;
    private javax.swing.JButton jButtonGhiFile;
    private javax.swing.JLabel jLabelCipherText;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelKhoa;
    private javax.swing.JLabel jLabelPlainText;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JTextField jTextFieldCipherText;
    private javax.swing.JTextField jTextFieldKhoa;
    private javax.swing.JTextField jTextFieldPlainText;
    // End of variables declaration//GEN-END:variables
}
