/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuan4;

/**
 *
 * @author thanh
 */

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;
public class Alice extends javax.swing.JFrame {
    
    KeyAgreement aliceKeyAgree;
    PublicKey bobPubKey;
    SecretKey aliceDesKey;
    Cipher aliceCipher;

    /**
     * Creates new form Alice
     */
    public Alice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmahoakab = new javax.swing.JTextField();
        btnkhoaa = new javax.swing.JButton();
        btnkhoab = new javax.swing.JButton();
        btnkhoachung = new javax.swing.JButton();
        btnmahoakab = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btngiaima = new javax.swing.JButton();
        txtkhoaa = new javax.swing.JTextField();
        txtkhoab = new javax.swing.JTextField();
        txtkhoachung = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnkhoaa.setText("Tạo khóa A");
        btnkhoaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoaaActionPerformed(evt);
            }
        });

        btnkhoab.setText("Hiện thị KB");
        btnkhoab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoabActionPerformed(evt);
            }
        });

        btnkhoachung.setText("Khóa chung");
        btnkhoachung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoachungActionPerformed(evt);
            }
        });

        btnmahoakab.setText("Mã hóa KAB");
        btnmahoakab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoakabActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Alice");

        jLabel2.setText("Khóa Alice :");

        jLabel3.setText("Khóa Bob");

        jLabel4.setText("Khóa KAB :");

        jLabel5.setText("Mã hóa KAB :");

        btngiaima.setText("Mã hóa / Giải mã");
        btngiaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btngiaima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmahoakab, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtkhoachung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txtkhoab, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtkhoaa, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnkhoachung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmahoakab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnkhoab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnkhoaa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkhoaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhoaa))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkhoab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhoab))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtkhoachung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhoachung))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmahoakab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmahoakab))
                .addGap(28, 28, 28)
                .addComponent(btngiaima)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkhoaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoaaActionPerformed
        // TODO add your handling code here:
        try{
            AlgorithmParameterGenerator paramGen= AlgorithmParameterGenerator.getInstance("DH");
            paramGen.init(512);
            AlgorithmParameters params= paramGen.generateParameters();

            DHParameterSpec dhSkipParamSpec=
            (DHParameterSpec) params.getParameterSpec(DHParameterSpec.class);

            System.out.println("Generating a DH KeyPair...");
            KeyPairGenerator aliceKpairGen=KeyPairGenerator.getInstance("DH");
            aliceKpairGen.initialize(dhSkipParamSpec);
            KeyPair aliceKpair=aliceKpairGen.generateKeyPair();

            System.out.println("Initializing the KeyAgreement Engine with DH private key");
            aliceKeyAgree=KeyAgreement.getInstance("DH");
            aliceKeyAgree.init(aliceKpair.getPrivate());

            byte[] alicePubKeyEnc=aliceKpair.getPublic().getEncoded();
            FileOutputStream fos=new FileOutputStream("D:/A.pub");
            fos.write(alicePubKeyEnc);
            fos.close();
            txtkhoaa.setText(alicePubKeyEnc.toString());
        }catch(Exception ex){}
    }//GEN-LAST:event_btnkhoaaActionPerformed

    private void btnkhoabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoabActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis=new FileInputStream("D:/B.pub");
            byte[] bkeyP=new byte[fis.available()];
            fis.read(bkeyP);
            fis.close();
            txtkhoab.setText(bkeyP.toString());
        }catch(Exception ex){}
    }//GEN-LAST:event_btnkhoabActionPerformed

    private void btnkhoachungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoachungActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis=new FileInputStream("D:/B.pub");
            byte[] bobPubKeyEnc=new byte[fis.available()];
            fis.read(bobPubKeyEnc);
            fis.close();

            KeyFactory aliceKeyFac= KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec=new X509EncodedKeySpec(bobPubKeyEnc);
            bobPubKey=aliceKeyFac.generatePublic(x509KeySpec);
            System.out.println("Executing PHASE1 of key agreement...");
            aliceKeyAgree.doPhase(bobPubKey, true);
            byte[] aliceSharedSecret= aliceKeyAgree.generateSecret();

            System.out.println("khoa chung: secret (DEBUG ONLY):"+CryptoUtil.toHexString(aliceSharedSecret));
            txtkhoachung.setText(CryptoUtil.toHexString(aliceSharedSecret));
        }catch(Exception ex){}
    }//GEN-LAST:event_btnkhoachungActionPerformed

    private void btnmahoakabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoakabActionPerformed
          // TODO add your handling code here:
        try{
            aliceKeyAgree.doPhase(bobPubKey, true);
            aliceDesKey=aliceKeyAgree.generateSecret("DES");
            txtmahoakab.setText(aliceDesKey.toString());
            
            BufferedWriter bw=null;
            
            String fileName="D:\\KhoaA.txt";
             
            bw=new
                BufferedWriter(new FileWriter(fileName));
            bw.write(aliceDesKey.toString());
            bw.close();
        }catch(Exception ex){}
    }//GEN-LAST:event_btnmahoakabActionPerformed

    private void btngiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaimaActionPerformed
        // TODO add your handling code here:
        DESCS des=new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btngiaimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngiaima;
    private javax.swing.JButton btnkhoaa;
    private javax.swing.JButton btnkhoab;
    private javax.swing.JButton btnkhoachung;
    private javax.swing.JButton btnmahoakab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtkhoaa;
    private javax.swing.JTextField txtkhoab;
    private javax.swing.JTextField txtkhoachung;
    private javax.swing.JTextField txtmahoakab;
    // End of variables declaration//GEN-END:variables
}
