/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuan4;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.interfaces.DHPublicKey;
import javax.crypto.spec.DHParameterSpec;

/**
 *
 * @author thanh
 */
public class Bob extends javax.swing.JFrame {
    KeyAgreement bobKeyAgree;
    PublicKey alicePubKey;
    SecretKey bobDesKey;
    Cipher bobCipher;

    /**
     * Creates new form Bob
     */
    public Bob() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngiaima = new javax.swing.JButton();
        txtmahoakab = new javax.swing.JTextField();
        btnkhoaB = new javax.swing.JButton();
        btnkhoakA = new javax.swing.JButton();
        btnkhoachung = new javax.swing.JButton();
        btnmahoakab = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtkhoaa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtkhoab = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtkhoachung = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btngiaima.setText("Mã hóa / Giải mã");
        btngiaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaimaActionPerformed(evt);
            }
        });

        btnkhoaB.setText("Tạo khóa B");
        btnkhoaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoaBActionPerformed(evt);
            }
        });

        btnkhoakA.setText("Hiển thị KA");
        btnkhoakA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoakAActionPerformed(evt);
            }
        });

        btnkhoachung.setText("Khóa chung");
        btnkhoachung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoachungActionPerformed(evt);
            }
        });

        btnmahoakab.setText("Mã hóa KAB");
        btnmahoakab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoakabActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Bob");

        jLabel2.setText("Khóa Bob :");

        jLabel3.setText("Khóa Alice :");

        jLabel4.setText("khoa KAB :");

        jLabel5.setText("Ma hoa KAB :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btngiaima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmahoakab, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtkhoachung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txtkhoab, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtkhoaa, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnkhoaB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnkhoakA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnkhoachung, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnmahoakab, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkhoaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhoaB))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkhoab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhoakA))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtkhoachung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhoachung))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmahoakab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmahoakab))
                .addGap(28, 28, 28)
                .addComponent(btngiaima)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaimaActionPerformed
        // TODO add your handling code here:
        DESCS des=new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btngiaimaActionPerformed

    private void btnkhoaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoaBActionPerformed
        // TODO add your handling code here:
        try{
            boolean read=false;
            while(!read){
                try{
                    FileInputStream fis=new FileInputStream("D:/A.pub");
                    fis.close();
                    read=true;
                }catch(Exception ex){}
            }

            FileInputStream fis=new FileInputStream("D:/A.pub");
            byte[] alicePubKeyEnc=new byte[fis.available()];
            fis.read(alicePubKeyEnc);
            fis.close();
            KeyFactory bobKeyFac=KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec=new X509EncodedKeySpec(alicePubKeyEnc);
            alicePubKey=bobKeyFac.generatePublic(x509KeySpec);

            DHParameterSpec dhParamSpec=((DHPublicKey)alicePubKey).getParams();

            System.out.println("Generating a DH KeyPair...");
            KeyPairGenerator bobKpairGen=KeyPairGenerator.getInstance("DH");
            bobKpairGen.initialize(dhParamSpec);
            KeyPair bobKpair=bobKpairGen.generateKeyPair();

            System.out.println("Initializing the KeyAgreement Engine with DH private key");
            bobKeyAgree=KeyAgreement.getInstance("DH");
            bobKeyAgree.init(bobKpair.getPrivate());

            byte[] bobPubKeyEnc=bobKpair.getPublic().getEncoded();
            FileOutputStream fos=new FileOutputStream("D:/B.pub");
            fos.write(bobPubKeyEnc);
            fos.close();
            txtkhoaa.setText(bobPubKeyEnc.toString());
        }catch(Exception ex){}
    }//GEN-LAST:event_btnkhoaBActionPerformed

    private void btnkhoakAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoakAActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis=new FileInputStream("D:/A.pub");
            byte [] bkeyP=new byte[fis.available()];
            fis.read(bkeyP);
            fis.close();
            txtkhoab.setText(bkeyP.toString());
        }catch(Exception ex){}
    }//GEN-LAST:event_btnkhoakAActionPerformed

    private void btnkhoachungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoachungActionPerformed
        // TODO add your handling code here:
        try{
            bobKeyAgree.doPhase(alicePubKey, true);
            byte[] bobSharedSecret=bobKeyAgree.generateSecret();
            System.out.println("khoa chung: secret (DEBUG ONLY):"+CryptoUtil.toHexString(bobSharedSecret));
            txtkhoachung.setText(CryptoUtil.toHexString(bobSharedSecret));
        }catch(Exception Ex){}
    }//GEN-LAST:event_btnkhoachungActionPerformed

    private void btnmahoakabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoakabActionPerformed
         // TODO add your handling code here:
        try{
             bobKeyAgree.doPhase(alicePubKey, true);
             bobDesKey=bobKeyAgree.generateSecret("DES");
             txtmahoakab.setText(bobDesKey.toString());
       


             BufferedWriter bw=null;

            String fileName="D:\\KhoaB.txt";

            bw=new
            BufferedWriter(new FileWriter(fileName));
            bw.write(bobDesKey.toString());
            bw.close();
        }catch(Exception ex){}
    }//GEN-LAST:event_btnmahoakabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngiaima;
    private javax.swing.JButton btnkhoaB;
    private javax.swing.JButton btnkhoachung;
    private javax.swing.JButton btnkhoakA;
    private javax.swing.JButton btnmahoakab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtkhoaa;
    private javax.swing.JTextField txtkhoab;
    private javax.swing.JTextField txtkhoachung;
    private javax.swing.JTextField txtmahoakab;
    // End of variables declaration//GEN-END:variables
}
