/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuan4;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.security.InvalidKeyException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.CipherInputStream;
import javax.crypto.CipherOutputStream;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESKeySpec;
import javax.swing.JOptionPane;

/**
 *
 * @author thanh
 */
public class DESCS extends javax.swing.JFrame {

    /**
     * Creates new form DESCS
     */
    public DESCS() {
        initComponents();
    }
    private int mode;
    private static void doCopy( InputStream is ,OutputStream os) throws IOException{
    byte[] bytes=new byte[64];
    int numBytes;
     while((numBytes=is.read(bytes)) !=-1)
    {
	os.write(bytes,0,numBytes);
    }
    os.flush();
    os.close();
    is.close();
}
    public static void encrypt(String key, InputStream is ,OutputStream os) throws Throwable{
    
            encryptOrDecrypt(key, Cipher.ENCRYPT_MODE, is, os);
    }
    public static void decrypt(String key, InputStream is ,OutputStream os) throws Throwable{
    
         encryptOrDecrypt(key, Cipher.DECRYPT_MODE, is, os);
    }
    public static void encryptOrDecrypt(String key,int mode, InputStream is ,OutputStream os) throws Throwable{
     
    DESKeySpec dks=new DESKeySpec(key.getBytes());
    SecretKeyFactory  skf=SecretKeyFactory.getInstance("DES");
    SecretKey  desKey = skf.generateSecret(dks);
    Cipher cipher =Cipher.getInstance("DES");
    if(mode==Cipher.ENCRYPT_MODE)
    {
	cipher.init(Cipher.ENCRYPT_MODE,desKey);
        CipherInputStream cis=new CipherInputStream(is,cipher);
        doCopy(cis,os);
    }
    else if(mode==Cipher.DECRYPT_MODE){
        cipher.init(Cipher.DECRYPT_MODE,desKey);
        CipherOutputStream cos=new  CipherOutputStream(os,cipher);
         doCopy(is,cos);
    }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnkhoab = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnghifile = new javax.swing.JButton();
        btngiaima = new javax.swing.JButton();
        btnallshow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtvanban = new javax.swing.JTextArea();
        txtkhoa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbanro = new javax.swing.JTextArea();
        btnmahoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnkhoaa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Văn bản");

        btnkhoab.setText("mo khoa b");
        btnkhoab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoabActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã hóa");

        btnghifile.setText("Ghi file");
        btnghifile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghifileActionPerformed(evt);
            }
        });

        btngiaima.setText("giai ma");
        btngiaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaimaActionPerformed(evt);
            }
        });

        btnallshow.setText("all show");
        btnallshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallshowActionPerformed(evt);
            }
        });

        txtvanban.setColumns(20);
        txtvanban.setRows(5);
        jScrollPane1.setViewportView(txtvanban);

        txtbanro.setColumns(20);
        txtbanro.setRows(5);
        jScrollPane2.setViewportView(txtbanro);

        btnmahoa.setText("Ma hoa");
        btnmahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoaActionPerformed(evt);
            }
        });

        jLabel1.setText("Input key");

        btnkhoaa.setText("mo khoa a");
        btnkhoaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoaaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btngiaima)
                                .addGap(66, 66, 66)
                                .addComponent(btnallshow))
                            .addComponent(txtkhoa)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnmahoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnkhoaa)
                        .addGap(36, 36, 36)
                        .addComponent(btnkhoab)
                        .addGap(29, 29, 29)
                        .addComponent(btnghifile)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmahoa)
                    .addComponent(btnkhoaa)
                    .addComponent(btnkhoab)
                    .addComponent(btnghifile))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngiaima)
                    .addComponent(btnallshow))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkhoabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoabActionPerformed
        // TODO add your handling code here:
        try{
            BufferedReader br=null;
            String fileName="D:\\KhoaB.txt";
            br=new BufferedReader (new FileReader(fileName));
            StringBuffer sb=new StringBuffer();

            JOptionPane.showMessageDialog(null, "Da mo file");
            char[] ca=new char[5];
            while(br.ready())
            {
                int len=br.read(ca);
                sb.append(ca, 0, len);

            }
            br.close();
            System.out.println("Du lieu la:"+" "+sb);
            String chuoi=sb.toString();
            txtkhoa.setText(chuoi);
        }catch(IOException ex)
        {
            Logger.getLogger(DESCS.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnkhoabActionPerformed

    private void btnghifileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghifileActionPerformed
        // TODO add your handling code here:
        try{
            BufferedWriter bw=null;
            String fileName="D:\\Des.txt";
            String s=txtvanban.getText();
            bw=new
            BufferedWriter(new FileWriter(fileName));
            bw.write(s);
            bw.close();
            JOptionPane.showMessageDialog(null,"Da ghi file");
            txtbanro.setText(s);
        }catch(IOException ex)
        {
            Logger.getLogger(DESCS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnghifileActionPerformed

    private void btngiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaimaActionPerformed
        // TODO add your handling code here:
        FileInputStream fis2=null;
        try{
            String key=txtkhoa.getText();
            fis2=new FileInputStream("D:\\EnDes.txt");
            FileOutputStream fos2=new FileOutputStream("D:\\DeDes.txt");
            decrypt(key, fis2,fos2);
            BufferedReader br =null;
            String fileName="D:\\DeDes.txt";
            br=new BufferedReader(new FileReader(fileName));
            StringBuffer sb=new StringBuffer();
            JOptionPane.showMessageDialog(null,"Da giai ma");
            char[] ca=new char[5];
            while(br.ready())
            {
                int len =br.read(ca);
                sb.append(ca, 0, len);
            }
            br.close();
            System.out.println("Du lieu la: "+" "+sb);
            String chuoi =sb.toString();
            txtbanro.setText(chuoi);
        }catch(Throwable ex){}
    }//GEN-LAST:event_btngiaimaActionPerformed

    private void btnallshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallshowActionPerformed
        // TODO add your handling code here:
        try{
            BufferedReader br=null;
            String fileName ="D:\\DeDes.txt";
            br=new BufferedReader(new FileReader(fileName));
            StringBuffer sb=new StringBuffer();
            JOptionPane.showMessageDialog(null,"Da mo file");
            char[] ca=new char[5];
            while(br.ready())
            {
                int len =br.read(ca);
                sb.append(ca, 0, len);
            }
            br.close();
            String ff="D:\\EnDes.txt";
            br=new BufferedReader(new FileReader(ff));
            StringBuffer sb1=new StringBuffer();
            char[] ca1=new char[5];
            while(br.ready())
            {
                int len =br.read(ca1);
                sb1.append(ca1, 0, len);
            }
            System.out.println("Du lieu la: "+" "+sb);
            String chuoi =sb.toString();
            String chuoi1 =sb1.toString();
            txtvanban.setText(chuoi);
            txtbanro.setText(chuoi1);

        }catch(IOException ex){
        }
    }//GEN-LAST:event_btnallshowActionPerformed

    private void btnmahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoaActionPerformed
        // TODO add your handling code here:
        try{
            String key=txtkhoa.getText();
            FileInputStream fis=new FileInputStream("D:\\Des.txt");
            FileOutputStream fos=new FileOutputStream("D:\\EnDes.txt");
            encrypt(key, fis, fos);
            JOptionPane.showMessageDialog(null,"Da ma hoa van ban");
        }catch(Throwable e){ e.printStackTrace();}
    }//GEN-LAST:event_btnmahoaActionPerformed

    private void btnkhoaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoaaActionPerformed
        // TODO add your handling code here:
        try{
            BufferedReader br=null;
            String fileName="D:\\KhoaA.txt";
            br=new BufferedReader (new FileReader(fileName));
            StringBuffer sb=new StringBuffer();

            JOptionPane.showMessageDialog(null, "Da mo file");
            char[] ca=new char[5];
            while(br.ready())
            {
                int len=br.read(ca);
                sb.append(ca, 0, len);

            }
            br.close();
            System.out.println("Du lieu la:"+" "+sb);
            String chuoi=sb.toString();
            txtkhoa.setText(chuoi);
        }catch(IOException ex)
        {
            Logger.getLogger(DESCS.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnkhoaaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DESCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DESCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DESCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DESCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DESCS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnallshow;
    private javax.swing.JButton btnghifile;
    private javax.swing.JButton btngiaima;
    private javax.swing.JButton btnkhoaa;
    private javax.swing.JButton btnkhoab;
    private javax.swing.JButton btnmahoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtbanro;
    private javax.swing.JTextField txtkhoa;
    private javax.swing.JTextArea txtvanban;
    // End of variables declaration//GEN-END:variables
}
